---
- name: Install software properties common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Install Nginx and PHP
  apt:
    name:
      - nginx
      - php{{ php_version }}
      - php{{ php_version }}-fpm
      - php{{ php_version }}-xml
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-curl
      - php{{ php_version }}-zip
      - php{{ php_version }}-ffi
      - unzip
      - git
      - acl
      - rsync
    state: present
    update_cache: yes

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Start PHP-FPM
  service:
    name: php{{ php_version }}-fpm
    state: started
    enabled: yes
